### ISSUE TITLE
Error: Can't find Python executable "python" in bitnami/node:8.6.0-r1-prod image

### ISSUE THREAD

**Issue by tuananh** [bitnami/bitnami-docker-node#109]
I got this error when `npm install` one of the native module.

Was working fine with `node:8.6.0-r0`. Try using `node:8.6.0-r1-prod` and i got this issue

```
Error: Can't find Python executable "python"
```

```
> /opt/bitnami/node/bin/node /opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure
    gyp ERR! configure error 
    gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
    gyp ERR! stack     at PythonFinder.failNoPython (/opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:483:19)
    gyp ERR! stack     at PythonFinder.<anonymous> (/opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:397:16)
    gyp ERR! stack     at F (/opt/bitnami/node/lib/node_modules/npm/node_modules/which/which.js:68:16)
    gyp ERR! stack     at E (/opt/bitnami/node/lib/node_modules/npm/node_modules/which/which.js:80:29)
    gyp ERR! stack     at /opt/bitnami/node/lib/node_modules/npm/node_modules/which/which.js:89:16
    gyp ERR! stack     at /opt/bitnami/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:42:5
    gyp ERR! stack     at /opt/bitnami/node/lib/node_modules/npm/node_modules/which/node_modules/isexe/mode.js:8:5
    gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:153:21)
    gyp ERR! System Linux 3.13.0-105-generic
    gyp ERR! command "/opt/bitnami/node/bin/node" "/opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "clean" "configure"
    gyp ERR! cwd /usr/src/app/offer-worker/node_modules/@newrelic/native-metrics
    gyp ERR! node -v v8.6.0
    gyp ERR! node-gyp -v v3.6.2
    gyp ERR! not ok 
    Error: Failed to execute install: Error: Failed to install module: Error: Failed to execute /opt/bitnami/node/bin/node /opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js clean configure: code 1; Error: Downloading is disabled.
```

**Comment by prydonius** [comment]
@tuananh as discussed in https://github.com/bitnami/bitnami-docker-node/pull/107#discussion_r142682926, the assumption is that you would copy prebuilt node modules (in the node_modules folder of your app) into the prod container and therefore the `npm install` would happen in the dev container.

I'm open to adding Python back to the prod container though if we think that is useful and that the above usecase isn't viable.

**Comment by prydonius** [comment]
cc @sameersbn

**Comment by tuananh** [comment]
python alone is not gonna work i think. native modules may require make and gcc as well.

so i think we should do as you suggest

> the assumption is that you would copy prebuilt node modules (in the node_modules folder of your app) into the prod container and therefore the npm install would happen in the dev container.

**Comment by sameersbn** [comment]
@tuananh Thanks for using the bitnami/node docker images. We are glad that you chose to use/experiment with the production image variants. We would really like to get your experiences and feedback. Feel free to send us your comments at containers@bitnami.com.

**Comment by tuananh** [comment]
Thanks for your work on this. The container image size is drastically reduced in this release 👍
