### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by robbygallo** [bitnami/bitnami-docker-node#114]
how to use gulp watch?

**Comment by juan131** [comment]
Hi @robbygallo 

Are you talking about this Node [File Watcher](https://github.com/floatdrop/gulp-watch)? You can simply install in on your Node container using NPM once it has been started or mount the tool from your host and run the NPM install as it's explained in the link below:

See: https://github.com/bitnami/bitnami-docker-node#running-a-nodejs-app-with-npm-dependencies
