### ISSUE TITLE
Common linux commands lost

### ISSUE THREAD

**Issue by ysilvela** [bitnami/bitnami-docker-node#116]
Hi,

I update my images to the last version of the docker and I can check that the image not have the common commands of linux like ps or top.

Why?

Thanks.

**Comment by ysilvela** [comment]
Solved executing apt-get update && apt-get install -y procps

But why you remove linux command in last version?

**Comment by chipironcin** [comment]
Hi @ysilvela 
This image is based on https://github.com/bitnami/minideb which aims to be a minimalist Debian-based image built specifically to be used as a base image for containers.

As these commands are not needed for the proper execution of NodeJS we have removed them from the base image to shrink it.

**Comment by sameersbn** [comment]
@ysilvela i believe @chipironcin addressed your query. Closing the support request, please re-open if you have further queries
