### ISSUE TITLE
Include yarn (package manager) in the container image

### ISSUE THREAD

**Issue by Angelmmiguel** [bitnami/bitnami-docker-node#117]
[Yarn](https://yarnpkg.com/en/) is a package manager for node, such as npm. It was launched 1 year ago and due to some features and a better performance, its usage has grown drastically and a lot of projects uses it as the default package manager. Actually, the official docker node image includes it. 

Personally, to have `yarn` in place it's a feature that I need in a node container image. Most of the time I have to create a `Dockerfile` to install Yarn.

Thanks!

**Comment by jotadrilo** [comment]
Hi @Angelmmiguel !

We should definitely work on adding `yarn` to our development image. Any concerns? cc/ @tompizmor @juan131

**Comment by juan131** [comment]
I agree with you @jotadrilo @Angelmmiguel ! I opened an internal task to include it and link it to this issue.

**Comment by juanitoddd** [comment]
Adding yarn by default would be awesome. 
What I did to have yarn in my container was to run the following commands inside my container:

- `apt remove cmdtest`
- `apt install gnupg apt-transport-https`
- `curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -`
- `echo "deb https://dl.yarnpkg.com/debian/ stable main" |  tee /etc/apt/sources.list.d/yarn.list`
- `apt update`
- `apt install yarn`

Hope it helps for folks trying to get yarn inside this image

**Comment by juan131** [comment]
Hi @juanitoddd 

Thanks for sharing the workaround! There's a internal task to include it in the future but we didn't have time to address it yet. We will update this issue as soon as we have more news.

**Comment by Angelmmiguel** [comment]
_Adding a comment to avoid this issue to be closed_

**Comment by juan131** [comment]
Thanks @Angelmmiguel 
Hopefully we'll address the corresponding task soon.

**Comment by carrodher** [comment]
Hi! I am closing this issue because we released the different node images including `yarn`. You can find it in the path.

Please, feel free to reopen it if it doesn't work as expected.
