### ISSUE TITLE
container are run as root

### ISSUE THREAD

**Issue by oupala** [bitnami/bitnami-docker-node#123]
**Description**

The bitnami docker node image is launched as root while your documentation said that you changed that (and that was a [notable change](https://hub.docker.com/r/bitnami/node)).

**Steps to reproduce the issue:**

1. launch a new container with `/bin/bash`: `docker run -it --rm bitnami/node /bin/bash`
2. type `whoami` and see that the user is `root`, not `1001`

**Describe the results you received:**

The user is `root`, not `1001`.

**Describe the results you expected:**

The user should not be `root`, but another user (probably `1001`, according to your documentation).

**Additional information you deem important (e.g. issue happens only occasionally):**

None.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea838
 Built:             Wed Nov 13 07:25:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea838
  Built:            Wed Nov 13 07:24:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.0-11-amd64
 Operating System: Debian GNU/Linux 9 (stretch)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 15.55GiB
 Name: hostname
 ID: BS66:XTKJ:KTJI:PAVO:C62U:LYUJ:DQN4:YAPS:Y6BO:UL6I:4G7P:OTLV
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http://proxy:8080/
 No Proxy: /var/run/docker.sock,localhost,127.0.0.1,10.193.0.0,10.194.0.0,.francetelecom.fr
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

- Output of `docker-compose version` (if applicable):

n/a

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

n/a

**Comment by juan131** [comment]
Hi @oupala 

Thanks for reporting this issue in the **README.md**

I don't know how that information was included there but the `bitnami/node` image has always been run as root by default (despite it can be executed as non-root).

Currently, the "runtime" images are executed as "root" by default since they're oriented for development.
