### ISSUE TITLE
Install Node.js in IBM Cloud

### ISSUE THREAD

**Issue by datta-TG** [bitnami/bitnami-docker-node#128]
Are you looking to start programming or use your Node.js applications in the IBM Cloud? This documentation will guide you on how to install Node.js on the IBM Cloud using the Kubernetes Service.

## Pre-requisites

You must have an account created in IBM Cloud. The account needs to either be *Pay-As-You-Go* or *Subscription*. Click [here](https://cloud.ibm.com/docs/account?topic=account-accounts "here") to read more.
If you have a Lite account, you can upgrade it. Click [here](https://cloud.ibm.com/docs/account?topic=account-account-getting-started#account-gs-upgrade "here") to learn how to upgrade.

## Step 1: Provision Kubernetes Cluster

* Click on the search section at the top of the main page, type Kubernetes, and then choose Kubernetes Service.

![Kubernetes1](https://user-images.githubusercontent.com/70336951/105741581-760ef180-5f08-11eb-98c6-d95acee0505e.PNG)

* In the new window, select between the free and standard type under "Pricing plan". Once selected, click on create.

![KubernetesPaid1](https://user-images.githubusercontent.com/70336951/105741685-9b9bfb00-5f08-11eb-9b72-291096db010f.PNG)

We'll choose the Standard Plan for this documentation as the Free Plan may fall short of resources when deploying your pods. We highly recommend using a Standard Plan with the hardware that suits you the best. If you're selecting the Standard Plan, please make sure you select the adequate requirements,

* Select your Kubernetes Version to be the latest available or the required one by your application. In this example, we have set it to be '1.18.13'.
* Select Infrastructure as 'Classic'.
* Leave Resource Group to 'Default'.
* Select Geography to the one that suits you better or that fits your infrastructure.
* Select Availability to be 'Single Zone' or 'Multi Zone' depending on your needs.
* Select a Worker Zone that suits you better or that fits your infrastructure.

![KubernetesPaid2](https://user-images.githubusercontent.com/70336951/105741704-a060af00-5f08-11eb-851c-23ad4bbcbea5.PNG)

* Select the number of workers in Worker Pool.
* Give your Worker Pool a name.
* Leave the Encrypt Local Disk option 'On'
* Choose 'Both private and public endpoints' on Master Service Endpoint

![KubernetesPaid4](https://user-images.githubusercontent.com/70336951/105741717-a48ccc80-5f08-11eb-8088-bdb8a73600be.PNG)

* Give your cluster a name in 'cluster-name'
* Provide the tags to your cluster and click on Create.

![KubernetesPaid5](https://user-images.githubusercontent.com/70336951/105741728-a9ea1700-5f08-11eb-9189-5fe2a23c06ca.PNG)

Wait a few minutes while your cluster is deployed.

![KubernetesPaid3](https://user-images.githubusercontent.com/70336951/105741748-af476180-5f08-11eb-82ad-7a3a2d2db777.PNG)

The following checkmark and the word 'normal' will appear once the Kubernetes Cluster is deployed. You can check it under your cluster section which is located in your *Resources List*.

![KubernetesPaid6](https://user-images.githubusercontent.com/70336951/105741772-b4a4ac00-5f08-11eb-8392-6e3450d6fe67.PNG)

## Step 2:  Deploy IBM Cloud Block Storage plug-in

* Click on the search section at the top of the main page, select IBM Cloud Block Storage, and click on it.

![Storage1](https://user-images.githubusercontent.com/70336951/105741802-bb332380-5f08-11eb-8547-fbce22392868.PNG)

* A new window opens, select the cluster and enter the name you want for this workspace, in this case, it will be called _storage-example_, accept the terms, click *Install* and wait a few minutes.

![StoragePaid2](https://user-images.githubusercontent.com/70336951/105741833-c1c19b00-5f08-11eb-9128-21721d29dfd3.PNG)

## Step 3: Install Node.Js

* Click on the search section at the top of the main page, type Node.js, and click on it.

![node1](https://user-images.githubusercontent.com/70336951/105741857-c8e8a900-5f08-11eb-9bf9-598f54c5415e.PNG)

* A new window opens, select the cluster and enter the name you want for the Node.js workspace, in this case, it will be called _node-example_, accept the terms and click on *Install*. You can modify the different installation parameters at the bottom. We will leave them by default as shown below, but you can read more about setting up the parameters [here](https://cloud.ibm.com/catalog/content/node "here").

![node2](https://user-images.githubusercontent.com/70336951/105751031-79f44100-5f13-11eb-9dfe-586f1728ab4e.PNG)

## Step 4: Verify Installation

* Go to *Resources List* in the Left Navigation Menu and click on *Kubernetes*.

![test1](https://user-images.githubusercontent.com/70336951/105741911-da31b580-5f08-11eb-9925-338704e20fc6.png)

* Click the *Actions* button and select *Web terminal*.

![test2](https://user-images.githubusercontent.com/70336951/105741948-e453b400-5f08-11eb-94b1-d861fa7c290f.PNG)

* A window opens to install the web terminal, click on install and wait a few minutes. The window will pop up at the buttom If the web terminal is already installed.

![test3](https://user-images.githubusercontent.com/70336951/105741970-eae22b80-5f08-11eb-829e-976cb80c02e2.PNG)

* Once you have installed the terminal, open it, and type the following command. It will show you the workspaces of your cluster. You can see *node-example* is now active.

`$ kubectl get ns`

![nodetest1](https://user-images.githubusercontent.com/70336951/105742050-051c0980-5f09-11eb-8ca2-b98158e37be9.PNG)

* You can then obtain more data about the service and it's pods.

`$ kubectl get pod -n NAMESERVICE -o wide`

![nodetest2](https://user-images.githubusercontent.com/70336951/105742072-0cdbae00-5f09-11eb-9b54-af801a755b47.PNG)

`$ kubectl get service -n NAME SERVICE`

![nodetest3](https://user-images.githubusercontent.com/70336951/105742088-1107cb80-5f09-11eb-8a83-b6f46edd43c8.PNG)

* Select the pod within your service using bash.

`$ kubectl exec --stdin --tty PODNAME -n NAMESPACE -- /bin/bash`

![nodetest4](https://user-images.githubusercontent.com/70336951/105742100-1533e900-5f09-11eb-8801-236f705c6daf.PNG)

* And finally, check if Node.js is correctly installed checking its version and its main commands by typing 'node'. You can also use your regular Node.js commands to start operating with it.

`$ node`

![nodetest5](https://user-images.githubusercontent.com/70336951/105742118-19f89d00-5f09-11eb-8039-34fed03b54c0.PNG)

You have finished the installation, enjoy your Node.js installation!

**Comment by carrodher** [comment]
Thanks for the info. As it seems that there is no issue we should take action and everything works properly, I am going to mark this issue as “Closed” so it can be used by other users looking for information as if it were documentation
