### ISSUE TITLE
Non Root User Image for bitnami/node:10.17.0-centos

### ISSUE THREAD

**Issue by nikhil-pt** [bitnami/bitnami-docker-node#133]
We are looking for a node image for bitnami/node:10.17.0-centos having non-root user as in our cluster we are following strict security policy which has a flag for disabling non-root user in image container.

**Comment by javsalgar** [comment]
Hi,

Did you find any issues trying to build the image with the node.js application and setting it to non-root user?

**Comment by govindkailas** [comment]
@javsalgar - we are looking to have `node.js` and `apache` reverse proxy to it. Something like this https://docs.bitnami.com/aws/infrastructure/nodejs/get-started/get-started/ 
Is there a ready-made docker image with the above configuration?

**Comment by Mauraza** [comment]
Hi @govindkailas,

No, sorry. We have an image of node and an image of apache, but not an image with both.

**Comment by SGauts** [comment]
Hey Team,

We are using PM2 along with the bitnami/node image.
We are facing the below errors while using the non-root user. 

`Error: EACCES: permission denied, mkdir '/.pm2'
    at Object.mkdirSync (fs.js:757:3)
    at mkdirpManualSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-manual.js:48:10)
    at mkdirpManualSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-manual.js:52:43)
    at mkdirpNativeSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:33:14)
    at Function.mkdirpSync [as sync] (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/opt/bitnami/node/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
Error: EACCES: permission denied, mkdir '/.pm2'
    at Object.mkdirSync (fs.js:757:3)
    at mkdirpManualSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-manual.js:48:10)
    at mkdirpManualSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-manual.js:52:43)
    at mkdirpNativeSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:33:14)
    at Function.mkdirpSync [as sync] (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:141:25)
    at new module.exports (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/opt/bitnami/node/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
Error: ENOENT: no such file or directory, open '/.pm2/module_conf.json'
    at Object.openSync (fs.js:443:3)
    at Object.writeFileSync (fs.js:1194:35)
    at module.exports.Client.initFileStructure (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:149:10)
    at new module.exports (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/opt/bitnami/node/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
Error: EACCES: permission denied, mkdir '/.pm2'
    at Object.mkdirSync (fs.js:757:3)
    at mkdirpManualSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-manual.js:48:10)
    at mkdirpManualSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-manual.js:52:43)
    at mkdirpNativeSync (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/lib/mkdirp-native.js:33:14)
    at Function.mkdirpSync [as sync] (/opt/bitnami/node/lib/node_modules/pm2/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:157:25)
    at new module.exports (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:38:8)
    at new API (/opt/bitnami/node/lib/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

                        -------------

__/\\\\\\\\\\\\\____/\\\\____________/\\\\____/\\\\\\\\\_____
 _\/\\\/////////\\\_\/\\\\\\________/\\\\\\__/\\\///////\\\___
  _\/\\\_______\/\\\_\/\\\//\\\____/\\\//\\\_\///______\//\\\__
   _\/\\\\\\\\\\\\\/__\/\\\\///\\\/\\\/_\/\\\___________/\\\/___
    _\/\\\/////////____\/\\\__\///\\\/___\/\\\________/\\\//_____
     _\/\\\_____________\/\\\____\///_____\/\\\_____/\\\//________
      _\/\\\_____________\/\\\_____________\/\\\___/\\\/___________
       _\/\\\_____________\/\\\_____________\/\\\__/\\\\\\\\\\\\\\\_
        _\///______________\///______________\///__\///////////////__


                          Runtime Edition

        PM2 is a Production Process Manager for Node.js applications
                     with a built-in Load Balancer.

                Start and Daemonize any application:
                $ pm2 start app.js

                Load Balance 4 instances of api.js:
                $ pm2 start api.js -i 4

                Monitor in production:
                $ pm2 monitor

                Make pm2 auto-boot at server restart:
                $ pm2 startup

                To go further checkout:
                http://pm2.io/


                        -------------

Error: ENOENT: no such file or directory, open '/.pm2/module_conf.json'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:343:35)
    at Object.Configuration.getAllSync (/opt/bitnami/node/lib/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/opt/bitnami/node/lib/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/opt/bitnami/node/lib/node_modules/pm2/lib/API.js:117:44)
    at Object.<anonymous> (/opt/bitnami/node/lib/node_modules/pm2/lib/binaries/CLI.js:22:11)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
fs.js:114
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/.pm2/pm2.log'
    at Object.openSync (fs.js:443:3)
    at module.exports.Client.launchDaemon (/opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:228:12)
    at /opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:104:10
    at /opt/bitnami/node/lib/node_modules/pm2/lib/Client.js:321:14
    at process._tickCallback (internal/process/next_tick.js:61:11)`

We tried a lot of different approaches to resolving this but none of them worked out.

Requesting your assistance for the same.

Thanks

**Comment by beltran-rubo** [comment]
hi @SGauts 

If you install pm2 to manage the process at the container build time, you can modify the permissions of the folder to be able to write/read there running as non-root. In your case the Dockerfile could be similar to this:

```
FROM bitnami/node

RUN npm install -g pm2
RUN useradd -r node && mkdir /home/node && chown -R node:node /home/node
USER node
```

That way the user 'node' would have privileges to run pm2 and save the status & logs into /home/node/.pm2. Could you try that?

**Comment by SGauts** [comment]
Hey @beltran-rubo ,

I made the changes you suggested are tried again. But sadly facing the same issue again.

Here is my dockerfile.

`#STAGE 1 - Building the Node app
FROM artfact-prd-vip.vmware.com:5001/bitnami/node:10.16.3-centos-7-r0 as taara-backend
# Create app directory
WORKDIR /app
RUN npm config set registry http://build-artifactory.eng.vmware.com:80/artifactory/api/npm/npm

COPY . .
RUN npm i --unsafe-perm && cp -R ./node_modules ./app
RUN npm install npm@latest -g 
RUN npm install pm2 -g
RUN npm install --unsafe-perm

RUN npm link pm2
RUN npm run forge

RUN useradd -r node && mkdir /app/node && chown -R node:node /app/node
USER node
# Expose the port the app runs in
EXPOSE 3000
# Serve the app
CMD ["pm2-runtime", "start", "ecosystem.config.js"]`

And below is my ecosystem.config.js file for the pm2 configs

`module.exports = {
  apps: [
    {
      name: 'Taara Backend',
      script: './server.js',
      node_args: '--max-http-header-size=32000',
      instances: 0,
      exec_mode: 'cluster',
      merge_logs: true,
      out_file: '/dev/null',
      log_date_format : "YYYY-MM-DD HH:mm Z",
      exp_backoff_restart_delay: 100,
      max_memory_restart: '1800M'
    }
  ],
};`

Please check it out and let me know if anything can be done.

Thanks

**Comment by beltran-rubo** [comment]
What is the error now? I was able to run a sample node app using this Dockerfile

```
FROM bitnami/node

RUN npm install -g pm2
RUN useradd -r node && mkdir /home/node && chown -R node:node /home/node

COPY sample-app /app
RUN chown -R node:node /app

USER node
WORKDIR /app
RUN npm install
EXPOSE 3000

CMD ["pm2-runtime", "start", "app.js"]
```

**Comment by SGauts** [comment]
Hey @beltran-rubo ,

We are now getting the below errors after incorporating your changes.

`Step 12/14 : RUN npm install
	 ---&#62 Running in 357db3812b94
	npm WARN checkPermissions Missing write access to /app/node_modules/pm2
	npm ERR! code EACCES
	npm ERR! syscall access
	npm ERR! path /app/node_modules/pm2
	npm ERR! errno -13
	npm ERR! Error: EACCES: permission denied, access '/app/node_modules/pm2'
	npm ERR!  [Error: EACCES: permission denied, access '/app/node_modules/pm2'] {
	npm ERR!   errno: -13,
	npm ERR!   code: 'EACCES',
	npm ERR!   syscall: 'access',
	npm ERR!   path: '/app/node_modules/pm2'
	npm ERR! }
	npm ERR! 
	npm ERR! The operation was rejected by your operating system.
	npm ERR! It is likely you do not have the permissions to access this file as the current user
	npm ERR! 
	npm ERR! If you believe this might be a permissions issue, please double-check the
	npm ERR! permissions of the file and its containing directories, or try running
	npm ERR! the command again as root/Administrator.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/node/.npm/_logs/2021-08-04T04_14_04_565Z-debug.log
	The command '/bin/sh -c npm install' returned a non-zero code: 243`


Below is our updated docker file

`
FROM bitnami/node

RUN npm install pm2 -g
RUN npm install --unsafe-perm
RUN npm link pm2

RUN useradd -r node && mkdir /home/node && chown -R node:node /home/node

COPY . /app
RUN chown -R node:node /app

USER node

WORKDIR /app
RUN npm install
EXPOSE 3000
CMD ["pm2-runtime", "start", "ecosystem.config.js"]`

Please suggest.

**Comment by javsalgar** [comment]
This is strange, the chown command should have changed all the ownership to `node:node`. In order to debug the issue, could you try to remove the `RUN npm install` line (with that the image should be created), and then try running the image like this?

```
docker run --rm -ti <nameoftheimage> bash
```

Then, inside, try executing the `npm install` command, if the permission errors appear again, could you check the permissions of the created folders, especially the failed ones?

**Comment by SGauts** [comment]
@beltran-rubo  @javsalgar 

We tried what you guys suggested.

Here are the error logs.

`Step 11/14 : RUN npm install
	 ---&#62 Running in 9a6aa116d244
	&#62 bcrypt@4.0.1 install /app/node_modules/bcrypt
	&#62 node-pre-gyp install --fallback-to-build
	node-pre-gyp WARN Using request for node-pre-gyp https download 
	node-pre-gyp WARN Pre-built binaries not installable for bcrypt@4.0.1 and node@14.17.4 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
	node-pre-gyp WARN Hit error EACCES: permission denied, mkdir '/app/node_modules/bcrypt/lib' 
	gyp WARN EACCES current user does not have permission to access the dev dir "/root/.cache/node-gyp/14.17.4"
	gyp WARN EACCES attempting to reinstall using temporary dev dir "/app/node_modules/bcrypt/.node-gyp"
	gyp WARN install got an error, rolling back install
	gyp WARN install got an error, rolling back install
	gyp ERR! configure error 
	gyp ERR! stack Error: EACCES: permission denied, mkdir '/app/node_modules/bcrypt/.node-gyp'
	gyp ERR! System Linux 3.10.0-1160.21.1.el7.x86_64
	gyp ERR! command "/opt/bitnami/node/bin/node" "/opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/app/node_modules/bcrypt/lib/binding/napi-v3" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
	gyp ERR! cwd /app/node_modules/bcrypt
	gyp ERR! node -v v14.17.4
	gyp ERR! node-gyp -v v5.1.0
	gyp ERR! not ok 
	node-pre-gyp ERR! build error 
	node-pre-gyp ERR! stack Error: Failed to execute '/opt/bitnami/node/bin/node /opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
	node-pre-gyp ERR! stack     at ChildProcess.&#60anonymous&#62 (/app/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
	node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
	node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
	node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
	node-pre-gyp ERR! System Linux 3.10.0-1160.21.1.el7.x86_64
	node-pre-gyp ERR! command "/opt/bitnami/node/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
	node-pre-gyp ERR! cwd /app/node_modules/bcrypt
	node-pre-gyp ERR! node -v v14.17.4
	node-pre-gyp ERR! node-pre-gyp -v v0.14.0
	node-pre-gyp ERR! not ok 
	Failed to execute '/opt/bitnami/node/bin/node /opt/bitnami/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/app/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/app/node_modules/bcrypt/lib/binding/napi-v3 --napi_version=8 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
	npm ERR! code ELIFECYCLE
	npm ERR! errno 1
	npm ERR! bcrypt@4.0.1 install: `node-pre-gyp install --fallback-to-build`
	npm ERR! Exit status 1
	npm ERR! 
	npm ERR! Failed at the bcrypt@4.0.1 install script.
	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /root/.npm/_logs/2021-08-04T09_53_17_620Z-debug.log`

Dockerfile used for this

`FROM bitnami/node

RUN npm install pm2 -g
RUN npm install --unsafe-perm
RUN npm link pm2

RUN useradd -r node && mkdir /home/node && chown -R node:node /home/node

COPY . /app
RUN chown -R node:node /app

WORKDIR /app
RUN npm install // it is failing here

USER node

EXPOSE 3000

CMD ["pm2-runtime", "start", "ecosystem.config.js"]`

**Comment by beltran-rubo** [comment]
I was able to reproduce that error installing `npm install bcrypt@4.0.1` as 'root' user. The node-gyp permission denied issue happens when you install node modules that require compilation with node-gyp.

If you install as 'node' user it works properly so it is needed to move the "USER node" directive before the `RUN npm install` action. I was able to install pm2 and bcrypt successfully. I would also suggest to remove the 'node_modules' folder into your 'app' folder to get a clean installation.

**Comment by SGauts** [comment]
Hey @beltran-rubo ,

When we move the "USER node" directive before the `RUN npm install` command, we get the below error.

	`Step 11/14 : USER node
	 ---&#62 Running in 828d6068e2fd
	Removing intermediate container 828d6068e2fd
	 ---&#62 6ab1943bf07f
	Step 12/14 : RUN npm install
	 ---&#62 Running in 07cd5199f667
	npm WARN checkPermissions Missing write access to /app/node_modules/pm2
	npm ERR! code EACCES
	npm ERR! syscall access
	npm ERR! path /app/node_modules/pm2
	npm ERR! errno -13
	npm ERR! Error: EACCES: permission denied, access '/app/node_modules/pm2'
	npm ERR!  [Error: EACCES: permission denied, access '/app/node_modules/pm2'] {
	npm ERR!   errno: -13,
	npm ERR!   code: 'EACCES',
	npm ERR!   syscall: 'access',
	npm ERR!   path: '/app/node_modules/pm2'
	npm ERR! }
	npm ERR! 
	npm ERR! The operation was rejected by your operating system.
	npm ERR! It is likely you do not have the permissions to access this file as the current user
	npm ERR! 
	npm ERR! If you believe this might be a permissions issue, please double-check the
	npm ERR! permissions of the file and its containing directories, or try running
	npm ERR! the command again as root/Administrator.
	
	npm ERR! A complete log of this run can be found in:
	npm ERR!     /home/node/.npm/_logs/2021-08-05T12_36_17_016Z-debug.log
	The command '/bin/sh -c npm install' returned a non-zero code: 243`

We don't copy the node_modules folder into the 'app' folder as it's not part of the git repo/files.

Please suggest.

**Comment by beltran-rubo** [comment]
I am not able to reproduce it, could you check if there is any different error or more information into the log?

```
$ cd /app
$ npm install pm2
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/sane/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pm2@5.1.0
added 178 packages from 170 contributors and audited 1226 packages in 16.784s


$ ./node_modules/.bin/pm2 --version
5.1.0

```

**Comment by nikhil-pt** [comment]
@javsalgar @beltran-rubo 

We tried the following Dockerfile:

`#STAGE 1 - Building the Node app
FROM bitnami/node
LABEL Maintainer="Gautam Sharma"
# Create app directory
RUN npm config set registry http://build-artifactory.eng.vmware.com:80/artifactory/api/npm/npm
RUN npm install pm2 -g
RUN npm install --unsafe-perm
RUN npm link pm2

RUN useradd -r node && mkdir /home/node && chown -R node:node /home/node

COPY . /app
RUN chown -R node:node /app
USER node
WORKDIR /app
#RUN npm install
# Expose the port the app runs in
EXPOSE 3000
# Serve the app
CMD ["pm2-runtime", "start", "ecosystem.config.js"]
`
The issue at hand seems to be that folders under /app/node_modules are with user node.
`node@a4471026c7bd:/app/node_modules$ ls -lrt
total 0
lrwxrwxrwx 1 node node 43 Aug 10 06:45 pm2 -> ../../opt/bitnami/node/lib/node_modules/pm2
`
But for folders inside pm2 where it is trying to install i.e. /app/node_modules/pm2 is having user as 1001.
`node@a4471026c7bd:/app/node_modules$ cd pm2
node@a4471026c7bd:/app/node_modules/pm2$ ls -lrt
total 200
-rw-r--r--  15 1001 1001    146 Oct 26  1985 unit_time
-rwxr-xr-x  15 1001 1001     87 Oct 26  1985 pm2
-rw-r--r--  15 1001 1001   3453 Oct 26  1985 paths.js
-rw-r--r--  15 1001 1001    298 Oct 26  1985 index.js
-rw-r--r--  15 1001 1001   5000 Oct 26  1985 constants.js
-rw-r--r--  15 1001 1001   6519 Oct 26  1985 README.md
-rw-r--r--  15 1001 1001     17 Oct 26  1985 LICENSE
-rw-r--r--  15 1001 1001  34516 Oct 26  1985 GNU-AGPL-3.0.txt
-rw-r--r--  15 1001 1001   2845 Oct 26  1985 CONTRIBUTING.md
-rw-r--r--  15 1001 1001 100464 Oct 26  1985 CHANGELOG.md
-rw-r--r--  15 1001 1001   5075 Aug 10 06:45 package.json
drwxr-xr-x   2 1001 1001   4096 Aug 10 06:53 bin
drwxr-xr-x   7 1001 1001   4096 Aug 10 06:53 lib
drwxr-xr-x 162 1001 1001   4096 Aug 10 06:53 node_modules
drwxr-xr-x   2 1001 1001   4096 Aug 10 06:53 types
`

Is this resulting in access denied error?

**Comment by javsalgar** [comment]
Hi,

What I don't fully understand here is, if you are using the Dockerfile above that has no references to 1001, where these permissions come from, it seems they are leftovers from previous attempts. Did you try removing the node_modules folder before running docker build?

**Comment by SGauts** [comment]
Hey @javsalgar ,

The node_modules folder is dynamically generated by the npm install command.
We don't have any pre-exisiting node_modules folder.

Thanks

**Comment by javsalgar** [comment]
Hi, in order for us to fully reproduce the issue, does the same issue happen with this sample application? 

https://github.com/franc-liuzzi/pm2-example-app

I was able to bulid the container with that, if it fails to you, it would help us to spot where the issue could be

**Comment by govindkailas** [comment]
@javsalgar - this is sorted out now, we had to change all the file permissions to `node` user.

**Comment by javsalgar** [comment]
Thanks for letting us know!
