### ISSUE TITLE
Non-root user cannot run npm/npx, exit status 243

### ISSUE THREAD

**Issue by regan-karlewicz** [bitnami/bitnami-docker-node#136]
### Name and Version

bitnami/node:16
bitnami/node:16.15.1

### What steps will reproduce the bug?

Using the following Dockerfile

```Dockerfile
FROM bitnami/node:16
RUN useradd -r -u 1001 -g root nonroot
USER nonroot
CMD ["/bin/sh"]
```
 
build and run it

```sh
docker build . -t bitnami-test && docker run -it bitnami-test
```

then run `npm` or `npx`

### What is the expected behavior?

`npm` should run and print help text, exit with status 0
`npx` should enter repl

### What do you see instead?

`npm` or `npx` does not output anything, exits with status 243

### Additional information

I have followed the directions in the [bitnami documentation](https://docs.bitnami.com/tutorials/deploy-custom-nodejs-app-bitnami-containers/) for setting up the non-root user 

If I repeat the steps above with the 16.15.0 version of the image, npm works as expected.

**Comment by regan-karlewicz** [comment]
@gongomgra Looks like that resolved the issue! Thank you for your help.

**Comment by gongomgra** [comment]
Hi @regan-karlewicz, glad it worked for you! We also updated our documentation with the mentioned change, so I'm closing this issue as solved.
