### ISSUE TITLE
Consider adding lts tag

### ISSUE THREAD

**Issue by joh-klein** [bitnami/bitnami-docker-node#139]
### Name and Version

bitnami/node:16

### What is the problem this feature will solve?

Keeping up with the latest LTS release.

### What is the feature you are proposing to solve the problem?

like `latest` add the `lts` tag to the most current lts node release.

**Comment by gongomgra** [comment]
Hi @joh-klein,

Thanks for your suggestion. Unfortunately, adding a `LTS` tag to the Node.js container is not in our roadmap, as we have standardize the tags for our products. You can get more information about this in the next links:

* https://github.com/bitnami/bitnami-docker-node#supported-tags-and-respective-dockerfile-links
* https://docs.bitnami.com/tutorials/understand-rolling-tags-containers/
